title: UNIDEV
description: Ji Hun, Choi's blog
url: http://kaizer21.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: About
   url: /index.html
 - title: Recent
   url: /recent.html
 - title: Articles
   url: /articles.html
 - title: Contact
   url: /contact.html

social:
   github: kaizer21
   facebook: 
   email: ghc21@naver.com

google_analytics: ""
