title: YEOUBI
description: 

url: http://mu29.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: About
   url: /index.html
 - title: Recent
   url: /recent.html
 - title: Articles
   url: /articles.html
 - title: Contact
   url: /contact.html

social:
   github: mu29
   facebook: mu29
   email: mu29gl@gmail.com

google_analytics: "UA-63387097-1"
